apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: factorio-ingress
  namespace: factorio
spec:
  entryPoints:
    - factorio-udp
  routes:
    - services:
        - name: factorio-service
          port: 34197
