apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio-host-volume
  namespace: factorio
  labels:
    directory: factorio
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /data/factorio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-host-claim
  namespace: factorio
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      directory: factorio