apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: factorio

volumes:
  # Mount data folder
  - volume: {{PROJECT_ROOT_DIR}}/data:/data
  # Add HelmCharConfig for Traefik
  - volume: {{PROJECT_ROOT_DIR}}/kubernetes/traefik/udp-entrypoint-helm-chart.yaml:/var/lib/rancher/k3s/server/manifests/traefik-config.yaml

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 34197:34197/udp
    nodeFilters:
      - loadbalancer